create table if not exists "users"
(
    id        bigint primary key generated by default as identity not null,
    name_user varchar(20)                                         not null,
    email     varchar(40) unique                                  not null
);

create table if not exists "items"
(
    id          bigint primary key generated by default as identity not null,
    name_item   varchar(40)                                         not null,
    description varchar(255)                                        not null,
    available   boolean                                             not null,
    owner_id    bigint references users (id)                        not null,
    request_id  bigint references users (id)                        not null
);
create table if not exists "bookings"
(
    id            bigint primary key generated by default as identity not null,
    start_booking TIMESTAMP WITHOUT TIME ZONE                         not null,
    end_booking   TIMESTAMP WITHOUT TIME ZONE,
    item_id       bigint                                              not null,
    booker_id     bigint                                              not null,
    status        varchar                                             not null
);

create table if not exists "requests"
(
    id           bigint primary key generated by default as identity not null,
    description  varchar(255)                                        not null,
    requestor_id bigint references users (id)                        not null
);
create table if not exists "comments"
(
    id        bigint primary key generated by default as identity not null,
    text      varchar(255)                                        not null,
    item_id   bigint references items (id)                        not null,
    author_id bigint references users (id)                        not null
)
